float:
  any:
  - base_args: ['@metric']
    constructor: MyAlgorithmBaseDimRed
    disabled: false
    docker_tag: ann-benchmarks-my-algorithm-base-dimred-240-224
    module: ann_benchmarks.algorithms.my_algorithm_base_dimred_240_224
    name: my-algorithm-base-dimred-240-224
    run_groups:
      M-24-240-224:
        arg_groups: [{M: 24, efConstruction: 500, alpha: 1.0, use_dim_reduction: false, reduction_threshold: 1, target_dims: [240, 224], reduction_type: "pca"}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-36-240-224:
        arg_groups: [{M: 36, efConstruction: 500, alpha: 1.0, use_dim_reduction: true, reduction_threshold: 1, target_dims: [240, 224], reduction_type: "pca"}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-48-240-224:
        arg_groups: [{M: 48, efConstruction: 500, alpha: 1.0, use_dim_reduction: true, reduction_threshold: 1, target_dims: [240, 224], reduction_type: "pca"}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-64-240-224:
        arg_groups: [{M: 64, efConstruction: 500, alpha: 1.0, use_dim_reduction: true, reduction_threshold: 1, target_dims: [240, 224], reduction_type: "pca"}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-96-240-224:
        arg_groups: [{M: 96, efConstruction: 500, alpha: 1.0, use_dim_reduction: true, reduction_threshold: 1, target_dims: [240, 224], reduction_type: "pca"}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]

      M-24-240:
        arg_groups: [{M: 24, efConstruction: 500, alpha: 1.0, use_dim_reduction: false, reduction_threshold: 1, target_dims: [240], reduction_type: "pca"}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-36-240:
        arg_groups: [{M: 36, efConstruction: 500, alpha: 1.0, use_dim_reduction: true, reduction_threshold: 1, target_dims: [240], reduction_type: "pca"}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-48-240:
        arg_groups: [{M: 48, efConstruction: 500, alpha: 1.0, use_dim_reduction: true, reduction_threshold: 1, target_dims: [240], reduction_type: "pca"}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-64-240:
        arg_groups: [{M: 64, efConstruction: 500, alpha: 1.0, use_dim_reduction: true, reduction_threshold: 1, target_dims: [240], reduction_type: "pca"}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-96-240:
        arg_groups: [{M: 96, efConstruction: 500, alpha: 1.0, use_dim_reduction: true, reduction_threshold: 1, target_dims: [240], reduction_type: "pca"}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]

      M-24-224:
        arg_groups: [{M: 24, efConstruction: 500, alpha: 1.0, use_dim_reduction: false, reduction_threshold: 1, target_dims: [224], reduction_type: "pca"}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-36-224:
        arg_groups: [{M: 36, efConstruction: 500, alpha: 1.0, use_dim_reduction: true, reduction_threshold: 1, target_dims: [224], reduction_type: "pca"}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-48-224:
        arg_groups: [{M: 48, efConstruction: 500, alpha: 1.0, use_dim_reduction: true, reduction_threshold: 1, target_dims: [224], reduction_type: "pca"}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-64-224:
        arg_groups: [{M: 64, efConstruction: 500, alpha: 1.0, use_dim_reduction: true, reduction_threshold: 1, target_dims: [224], reduction_type: "pca"}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-96-224:
        arg_groups: [{M: 96, efConstruction: 500, alpha: 1.0, use_dim_reduction: true, reduction_threshold: 1, target_dims: [224], reduction_type: "pca"}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]