float:
  angular:
  - base_args: {}
    constructor: Scann
    disabled: false
    docker_tag: ann-benchmarks-scann
    module: ann_benchmarks.algorithms.scann
    name: scann
    run_groups:
      scann1:
        args: [[2000], [0.2], [2], [dot_product]]
        query_args: [[[1, 30], [2, 30], [4, 30], [8, 30], [30, 120], [35, 100], [
              40, 80], [45, 80], [50, 80], [55, 95], [60, 110], [65, 110], [75, 110],
            [90, 110], [110, 120], [130, 150], [150, 200], [170, 200], [200, 300],
            [220, 500], [250, 500], [310, 300], [400, 300], [500, 500], [800, 1000]]]
      scann2:
        args: [[1500], [0.55], [1], [dot_product]]
        query_args: [[[1, 30], [2, 30], [4, 30], [8, 30], [8, 25], [10, 25], [12,
              25], [13, 25], [14, 27], [15, 30], [17, 30], [18, 40], [20, 40], [22,
              40], [25, 50], [30, 50], [35, 55], [50, 60], [60, 60], [80, 80], [100,
              100]]]
      scann3:
        args: [[1000], [0.2], [1], [dot_product]]
        query_args: [[[1, 30], [2, 30], [4, 30], [8, 30], [9, 25], [11, 35], [12,
              35], [13, 35], [14, 40], [15, 40], [16, 40], [17, 45], [20, 45], [20,
              55], [25, 55], [25, 70], [30, 70], [40, 90], [50, 100], [60, 120], [
              70, 140]]]
      scann4:
        args: [[1400], [0.15], [3], [dot_product]]
        query_args: [[[1, 30], [4, 30], [9, 30], [16, 32], [25, 50], [36, 72], [49,
              98], [70, 150], [90, 200], [120, 210], [180, 270], [210, 330], [260,
              400], [320, 500], [400, 600], [500, 700], [800, 900]]]
  euclidean:
  - base_args: {}
    constructor: Scann
    disabled: false
    docker_tag: ann-benchmarks-scann
    module: ann_benchmarks.algorithms.scann
    name: scann
    run_groups:
      scann1:
        args: [[600], [.nan], [2], [squared_l2]]
        query_args: [[[4, 40], [3, 30], [6, 60], [8, 74], [9, 78], [10, 82], [11,
              85], [13, 100], [16, 120], [20, 140], [30, 180], [35, 240], [50, 360]]]
      scann2:
        args: [[2000], [.nan], [4], [squared_l2]]
        query_args: [[[10, 100], [15, 140], [25, 160], [35, 190], [40, 200], [45,
              220], [50, 240], [60, 250], [70, 300], [80, 400], [100, 500], [120,
              600], [150, 800], [200, 900]]]
      scann3:
        args: [[100], [.nan], [4], [squared_l2]]
        query_args: [[[2, 20], [3, 20], [3, 30], [4, 30], [5, 40], [8, 80]]]
