bit:
  hamming:
  - base_args: [[mih/bin/mihwrapper]]
    constructor: BitSubprocessPrepared
    disabled: true
    docker_tag: ann-benchmarks-mih
    module: ann_benchmarks.algorithms.subprocess
    name: mih
    run_groups:
      base:
        args:
          chunk-factor: [0.2, 0.5, 0.8]
          d: '@dimension'
          r: [0, 2, 3]
