float:
  any:
  - base_args: ['@metric']
    constructor: DummyAlgoSt
    disabled: true
    docker_tag: ann-benchmarks-dummy_algo
    module: ann_benchmarks.algorithms.dummy_algo
    name: dummy-algo-st
    run_groups:
      empty:
        args: []
  - base_args: ['@metric']
    constructor: DummyAlgoMt
    disabled: true
    docker_tag: ann-benchmarks-dummy_algo
    module: ann_benchmarks.algorithms.dummy_algo
    name: dummy-algo-mt
    run_groups:
      empty:
        args: []
