float:
  any:
  - base_args: ['@metric']
    constructor: MyAlgorithmDiversity
    disabled: false
    docker_tag: ann-benchmarks-my-algorithm-diversity
    module: ann_benchmarks.algorithms.my_algorithm_diversity
    name: my-algorithm-diversity
    run_groups:
      M-12:
        arg_groups: [{M: 12, efConstruction: 500, eps_rad: 0.3}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-16:
        arg_groups: [{M: 16, efConstruction: 500, eps_rad: 0.25}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-24:
        arg_groups: [{M: 24, efConstruction: 500, eps_rad: 0.2}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-36:
        arg_groups: [{M: 36, efConstruction: 500, eps_rad: 0.17}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-4:
        arg_groups: [{M: 4, efConstruction: 500, eps_rad: 0.5}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-48:
        arg_groups: [{M: 48, efConstruction: 500, eps_rad: 0.15}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-64:
        arg_groups: [{M: 64, efConstruction: 500, eps_rad: 0.13}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-8:
        arg_groups: [{M: 8, efConstruction: 500, eps_rad: 0.35}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-96:
        arg_groups: [{M: 96, efConstruction: 500, eps_rad: 0.1}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
