float:
  any:
  - base_args: ['@metric']
    constructor: CKDTree
    disabled: true
    docker_tag: ann-benchmarks-ckdtree
    module: ann_benchmarks.algorithms.ckdtree
    name: ckdtree
    run_groups:
      ball:
        args: [[10, 20, 40, 100, 200, 400, 1000]]
