float:
  any:
  - base_args: ['@metric']
    constructor: MyAlgorithmPrune
    disabled: false
    docker_tag: ann-benchmarks-my-algorithm-prune-2-50
    module: ann_benchmarks.algorithms.my_algorithm_prune_2_50
    name: my-algorithm-prune-2-50
    run_groups:
      M-12:
        arg_groups: [{M: 12, efConstruction: 500, alpha: 2.5}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-16:
        arg_groups: [{M: 16, efConstruction: 500, alpha: 2.5}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-24:
        arg_groups: [{M: 24, efConstruction: 500, alpha: 2.5}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-36:
        arg_groups: [{M: 36, efConstruction: 500, alpha: 2.5}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-4:
        arg_groups: [{M: 4, efConstruction: 500, alpha: 2.5}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-48:
        arg_groups: [{M: 48, efConstruction: 500, alpha: 2.5}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-64:
        arg_groups: [{M: 64, efConstruction: 500, alpha: 2.5}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-8:
        arg_groups: [{M: 8, efConstruction: 500, alpha: 2.5}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-96:
        arg_groups: [{M: 96, efConstruction: 500, alpha: 2.5}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
